In [2]:
import numpy as np
import pandas as pd
from datetime import datetime
# from prawcore.exceptions import Forbidden
from prawcore import PrawcoreException

In [8]:
import copy
abc=copy.deepcopy(df)

In [124]:
abc

,title,text,time,num_comments,num_upvotes,upvote_ratio,redditor
0,I'm trapped,16 y.o. from South Korea here. I failed everyt...,2020-07-10 04:54:34,288,3625,1.00,bird-sniffer
1,My girlfriend killed herself a week after we b...,Hello. I don't really know how to start this. ...,2019-06-21 01:54:11,188,3225,0.99,Throw6524285
2,Anyone else not want to die and not want to ki...,,2020-02-25 16:51:01,326,2981,1.00,cleopatra_97
3,Raped in front of my girlfriend. feeling like ...,"\n\nI don't know what to say or do, I just fe...",2019-12-09 21:41:43,364,2803,0.99,Fantastic-Profession
4,“If you truly wanted to kill yourself and wasn...,"Yeah because I DONT WANT TO FUCKING DO IT, but...",2020-05-27 06:56:15,75,2656,1.00,Oels2
...,...,...,...,...,...,...,...
495,Always changing mind over suicide,Ever had this feeling? One moment you feel a s...,2020-02-09 13:13:21,33,441,0.99,schrodingerscat15
496,"I have never had affection in my life, respect...","Some backstory is needed here.\n\nI'm a girl, ...",2019-12-21 13:59:37,30,440,0.99,95girl
497,im extremely tired.,"Not even sure if i'll make it past today, im e...",2019-08-07 11:02:49,31,443,0.99,LUVVERY
498,Im ugly inside and out,Im a fucking failure. What’s the point of even...,2020-05-14 19:15:29,34,433,0.99,Aw-Jee
499,I Can Always Just Die After Graduation,I don't think I want to continue living in thi...,2020-01-03 18:22:29,44,437,0.99,rainbowtrout97

In [180]:
df.to_csv("suicidewatch.csv")

In [ ]:

# parsed_date = datetime.utcfromtimestamp(df[time][0])
# year = parsed_date.year
# month = parsed_date.month
# day = parsed_date.day

In [ ]:
#All posts of redditors

In [117]:
redditor_list=df['redditor'].astype('str').tolist()
print(len(redditor_list))
redditor_list = list(filter(lambda x: x!= 'None', redditor_list)) 
print(len(redditor_list))

500
454

In [118]:
user_df=pd.DataFrame()
user_df['redditor']=redditor_list
user_df['title'] = np.empty((len(user_df), 0)).tolist()
user_df['text'] = np.empty((len(user_df), 0)).tolist()
user_df['subreddit'] = np.empty((len(user_df), 0)).tolist()
# user_df.set_index("redditor", inplace = True) causing errors
user_df[0:5]

               redditor title text subreddit
0          bird-sniffer    []   []        []
1          Throw6524285    []   []        []
2          cleopatra_97    []   []        []
3  Fantastic-Profession    []   []        []
4                 Oels2    []   []        []

In [119]:
# i=0
for i in range(len(user_df)):
#for i in range(10):
#     l=[]
#     for comment in reddit.redditor("user").comments.new(limit=100):
#         l.append(comment.body.split("\n", 1)[0][:79])
#     user_df['comments'][i]=l
#     i+=1
    ti=[]
    te=[]
    sr=[]
    try:
        for submission in reddit.redditor(redditor_list[i]).submissions.top("all"):
#             if(len(user_df["title"][user])==0):
            ti.append(submission.title)
            te.append(submission.selftext)
            sr.append(submission.subreddit)
        user_df["title"][i]=ti
        user_df["text"][i]=te
        user_df["subreddit"][i]=sr
        print(i,user_df["redditor"][i])
#                 user_df["title"][user]=ti
#                 user_df["text"][user]=te
#             else:
#                 print(i,"not working",user)
                    
            
        
#         i+=1
    except PrawcoreException as err:
        print("exception occured")
        print(i,err)

0 bird-sniffer
1 Throw6524285
2 cleopatra_97
3 Fantastic-Profession
4 Oels2
5 hddineejbe
6 Alexut-
7 im-not-worth-it
8 QandeelH
9 ManiacalSuicidal
10 frankdowntown
11 Sue-uh-side-all
12 Bittybot5000
13 Tamiaxoxo00
14 zmrly
15 tblampied
16 SQLwitch
17 Gretel_PX
18 SQLwitch
19 nbailey73
20 ghostiic
21 TheDarkVixen
22 ghostiic
23 daziesandconfuzed
24 alexanderdamhethicc
25 SQLwitch
26 PurplePlum26
27 lucijasworld
28 penwryte
29 FR1STYLE21
30 herry720
31 Prof_Gutnacht
32 lueezer
33 annoyedpisces
34 dy1ngal0n3isfine
35 SadDepressed_Boy
36 _sadboi_halp_
37 cowchunks
38 Jasmine1919
39 huntychuu
40 Show_Us_Your_Fridge
41 SQLwitch
42 kissgene
43 idunnorandomthrowawa
44 jraelee
45 notbigay
46 fuckmystupidlife555
47 GodCreatedHell
48 iamconfusedta
49 methylphenidate1
50 Komorxbi
51 skidzy32
52 hardcorefizzting
53 theserottendays
54 1stDegreeBoo-Urns
55 alicefb
56 shihan1714
57 Vegetable-Echo
58 psychokilla-420
59 TehDragonGuy
60 throwaway222888888
61 moIIsxo
62 DreamFuck
63 ahhhhthrowww
64 throwawayiguess12344
65 Legosi13
66 mvp0909
67 Vladmir_the_romancer
68 LittleRedLamps
69 truleota
70 TaRoWa03
71 starry-night-230
72 SQLwitch
73 Bittybot5000
74 MerchantOfUndeath
75 Taylina
exception occured
76 received 403 HTTP response
77 alexamurillo
78 milkies_
79 lilpeepmyself
80 Dyslexic_Wvyern
81 herry720
82 coocoocoo56
83 Diggy84
84 Vuraxis
85 throw-me-away-sorry
86 lost-cause-throwaway
87 Lydthecatmom
88 Flawless_Cub
89 NollinVoid
90 ThisIsMy107thAccount
91 Itz_gigiiiii
92 fromaustt
93 CatLick-Carwash
94 oimaddie
95 drugdealingaccount
96 NiqPat
97 ryuukaiser45
98 WishIDidntCareSoMuch
99 mpgd8
100 JuSt-m0nIKA
101 beepboopquestions
102 xcrossq
exception occured
103 received 403 HTTP response
104 thebigkitchen
105 ThatMLGDuck
106 alienvampire444
107 yeahonmythrowaway
108 restistancewater
109 mr-vizla
110 homeless_knight
111 paul-anderson79
112 lanahbanana
113 natoni11
114 throwaway71459
115 sunshinesaddness
116 aixlaelina
117 methylphenidate1
118 Gurley78
119 Business_Echo
120 enlighteningleaves
121 caramel_raspberry
122 heregirl19
123 DaBMz
124 MetaphoricallyDead
125 Bigboicait
126 BigWungusBill
127 DullKole
128 RKG1998
129 idkwhattoputlol69
130 Nick--2003
131 MaveeL
132 Christian240
133 restlesssheep
134 drauch52
135 ca_tastrophe
136 tellmeapart
137 Thr0wawayJM
138 elacatz
139 OsakaReject
140 sammy1996x
141 joemamma8393
142 everyfcknameistakn
143 bitemefothermucker
144 Snow-wolf-19
145 Guypersonmcdudeman
146 J_Sky9432
147 ThebodyofTyler
148 vr16
149 throwaway2233445566_
150 ImAPerson_Hi
151 Grand_A_
152 WrongResult
153 weakbrainedwaste
154 DarelMelanie
155 DemonicDragon25
156 sarahlynn000
157 throwRA44440126
158 Qewrew
159 TiredOfBeingMediocre
160 HaThatsAGoodOne
161 iwannalickthesky
162 AlwaysNang
163 darkgirl1234s
164 coronado_dutroux
165 Crispyfetus69
166 Macsilver18
167 mmortimer17
168 itsuckstobehere
169 Frederix_
170 StopPanicking
171 urbanmicah
172 lanston4500
173 OceanBlueTiles
174 dormi890
175 Pinks_62
176 nolatravis
177 Marterpy
178 elusive1988
179 radiancesons
180 pencilwithnoeraser
181 AwfulBother
182 hlm1999
183 velzerat
184 MyDyingOpeth92
185 spidercelery
186 _cooph_
187 birds-birrrds
188 Bit3stuff
189 wanna-be-unbirthed
190 swtalmao
191 Iatechickenpenne
192 haojiubujian1
193 SilverSpotter
194 Avocadosis
195 August_Tries
196 vitaiterest
197 dis-moi-la-verite
198 w0lfmn15
199 i_ave
200 Avocqd0
201 Paige_4o4
202 lanahbanana
203 Heckbegone
204 emteemirror
205 fitzthefox
206 immotokay
207 Sertzul79
208 ProperUgly
209 RegularlyAlive
210 DecentBreadfruit
211 maladaptive-MOSalt
212 throwaway9572618
213 Marikuroo
214 floralfragments
215 Mastrr_Shifu
216 kaemsa
217 goodbyeveryone363636
218 twistedtearz
219 hiimhaanh
220 Bittybot5000
221 hiraethnoir
222 17yrcub
223 hahahahakms
224 yaposiclese467
225 lajap
226 legomenon_h
227 flowerynight
228 throwaway151a4
229 livw17
exception occured
230 received 403 HTTP response
231 catladyKT
232 bdizzz
exception occured
233 received 403 HTTP response
234 IMightBeAZombie_
235 OhNoMelon313
236 M1st4ken
237 GriefGirl
238 that-depressed-moon
239 ParpikaJnomes
240 Human214563246
241 Wumboing12
242 sugar-sushi
243 ScreamingSkipBayless
244 flickbreeze2003
245 obiwankitnoble
246 DrakeDarkholme
247 Nothing_2_Live_4
248 SmushyKidK
249 OFWTGKA
250 shauntless
251 barelybouyant
252 Thorawaylife
253 mcsbeat
254 MacoroniCheeze
255 miroldinho
256 EastSky_
257 Little_Kurshten
258 TheOGBoner69
259 ex-is-ten-tial
260 Symon_joestar
261 throwawaaayyyyylol
262 quirkycat8657
263 CapKind
264 accidentallyhappied
265 throwawayinnit96
266 ckrikelis
267 im-sorry-I-cant
268 ChardonnayInTheGrave
269 Prof_Gutnacht
270 SausageSlam
271 alice_and_cheshire
272 throwawayy83828283
273 flakeeight
274 queenManiac97
275 thorthrowrha
276 throwaway63729199363
277 herbstwinde
278 whyamisosadthrowaway
279 SebastianScarlet
280 fuxkle
281 soapsoupsoapsoup
282 edmvlpz
283 December18th
284 DeadPoohl
285 72744838
286 543iam
287 alwaysvoidlust
288 Karok245
289 flyingdown1878
290 MiserableSlip
291 throwaway52b
292 Jaisinwnw12322
293 wedreaminthedark
294 throwaway468248
295 M548
296 JGsweets
297 oofiies
298 herry720
299 RelatablePanic
300 ChocolateSenpai5
301 bloodvirgo
302 bladesoulgemini
303 iwannadiecuzisuck
304 83austin83
305 vskskfba
306 forworse2020
307 hackerinoez
308 L0vlyMarie
309 impeccablemix
310 72744838
311 honeyandcrumbles
312 stupid-snail-farmer
313 exititall97
314 Valtorix28
exception occured
315 received 403 HTTP response
316 its_that_guy_andrew
317 Sealabjaster
318 _throwthisout_
319 SQLwitch
320 loserfatass
321 dy1ngal0n3isfine
322 -BrainDead
323 amal98
324 ShouldHaveStayedIn16
325 PB_And_J_7123
326 beluirina
327 whocares4000
328 pocoboi
329 throwawaysuicideman
330 comefuckingshootme
331 retiredass
332 Bipolargirlfriend00
333 rosebudsav
334 M1st4ken
335 shelbystlr20
336 Anonweirdo039
337 Whylivewithnolove
338 lonesome-dreams
339 SilverScreen246
340 nothing_left_
341 Episodix
342 KingofJKU
343 throwaway729941
344 Notaredditorsorry
345 whythooy
346 honeyandcrumbles
347 amybubbles07
348 Raphael3655
349 shedoesntknowhername
350 nomnomair
351 explsionsinthesky
352 pokachipokachi
353 FastRepair
354 Complete_Employ
355 Zerokelvin7792
356 TKD_Life
357 DecentBreadfruit
358 Caterworm
359 H20verload1
360 loserfatass
361 Samhain13813
362 gengar_i
363 dreworbuskeridunno
364 Stuck-In-A-Hole
365 TalionTheWorstRanger
366 ProcrastinatingDeath
367 ijbgtrdzaq
368 AverageAtelierGamer
369 xailbail
370 thatoneboy135
371 DepressedSebi
372 What_I_do_45
373 JakePaul4lyfe
374 bunniesandbabies
375 mattiscool19
376 rumblemania
377 WalrusFTW
378 LittleRedLamps
379 snakesnack148
380 drauch52
381 aNewReality34
382 Jesullaneda
383 theRealDeep
384 KarsonKrusher
385 bluecrystal89
exception occured
386 received 403 HTTP response
387 TheSadMadBadOne
388 IAmBatman412
389 givenup7
390 kwan123456789
391 thro-way06
392 godoge899
393 flyingbeetlekites
394 tellmepleaseiloveyou
395 DeadAlive69
396 WhiteBaconJeb
397 BodiC
398 dy1ngal0n3isfine
399 PlaneTough
400 freemefromthishell_
401 Throwaway0y000
402 SuperSonic096
403 ghostingfamily
404 jnfn
405 maybeitsnisan
406 nifefite1488
407 snakesnack148
408 _AnnairdA_
409 throwaway9478210334
410 ensam_och_ledsen
411 libratd98
412 Gabe_Newell_pornhub
413 G0rdo1
414 OneAndDone8989
415 thecapriciousbitch
416 LukinSawyer
417 17frees
418 SadPersonHelpsYou
419 methylphenidate1
420 Bush_Baby_69_PL
421 dy1ngal0n3isfine
422 nidza1
423 thowawaymillion
424 throwaway0090090090
425 OnlyOneToShine
426 SamBeeTee
427 osira_rose
428 Lord_Lamington
429 CantyCoyote
430 slimsebo
431 SaltyBizkitt
432 closetperv69
433 QuccSpudz
434 methylphenidate1
435 RaNdOmAcC20202020
436 yeahonmythrowaway
437 throwaway61394
438 MaysaFox
439 NYSadPerson
440 BonkersinYonkers2019
441 Gotchabxtch
442 naunga
443 kaykay101111
444 YeetItAway2020
445 BB960228
exception occured
446 received 403 HTTP response
447 trekiebabe
448 WhyRedTape
449 OmnisMorir
450 AugustIsLonely
451 schrodingerscat15
452 95girl
453 LUVVERY

In [120]:
user_df

,redditor,title,text,subreddit
0,bird-sniffer,"[Korean High School Life Starter Pack, ""What L...","[, , 16 y.o. from South Korea here. I failed e...","[starterpacks, starterpacks, SuicideWatch, sta..."
1,Throw6524285,[My girlfriend killed herself a week after we ...,[Hello. I don't really know how to start this....,[SuicideWatch]
2,cleopatra_97,[Anyone else not want to die and not want to k...,"[, Hi - I’m a 22F and have been proposed to by...","[SuicideWatch, MuslimMarriage, MakeupAddiction..."
3,Fantastic-Profession,[Raped in front of my girlfriend. feeling like...,"[ \n\nI don't know what to say or do, I just f...","[SuicideWatch, Needafriend, Needafriend, gainit]"
4,Oels2,[“If you truly wanted to kill yourself and was...,"[Yeah because I DONT WANT TO FUCKING DO IT, bu...","[SuicideWatch, depression, depression, depress..."
...,...,...,...,...
449,OmnisMorir,"[I lived, Overdosing Soon., I lied, but today ...","[I wrote a post [On March 19, 2020](https://ww...","[SuicideWatch, SuicideWatch, SuicideWatch, Sui..."
450,AugustIsLonely,"[So how long until it “gets better”?, What’s a...","[Why should one not consider suicide?, , Fuck ...","[SuicideWatch, AskReddit, lonely, findareddit,..."
451,schrodingerscat15,"[Always changing mind over suicide, I wanna se...",[Ever had this feeling? One moment you feel a ...,"[SuicideWatch, Avatar_Kyoshi, korrasami, Avata..."
452,95girl,"[HiyajoSafina!, Okakuri's tsundere child, Aaaa...","[, , , Some backstory is needed here.\n\nI'm a...","[steinsgate, steinsgate, steinsgate, SuicideWa..."
453,LUVVERY,"[Just like some pet owners don't deserve pets,...","[[removed], , , crippled physically or mentall...","[Showerthoughts, Piracy, EtikaRedditNetwork, A..."

In [121]:
for i in range(len(user_df)):
    print(i)
    if (len(user_df['title'][i])==0):
        user_df.drop(i, inplace=True)
        print(i,"del")

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
76 del
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
103 del
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
230 del
231
232
233
233 del
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
315 del
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
386 del
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
446 del
447
448
449
450
451
452
453

In [122]:
import copy
user_df.index = range(len(user_df))
user_df
#xyz=copy.deepcopy(user_df)

,redditor,title,text,subreddit
0,bird-sniffer,"[Korean High School Life Starter Pack, ""What L...","[, , 16 y.o. from South Korea here. I failed e...","[starterpacks, starterpacks, SuicideWatch, sta..."
1,Throw6524285,[My girlfriend killed herself a week after we ...,[Hello. I don't really know how to start this....,[SuicideWatch]
2,cleopatra_97,[Anyone else not want to die and not want to k...,"[, Hi - I’m a 22F and have been proposed to by...","[SuicideWatch, MuslimMarriage, MakeupAddiction..."
3,Fantastic-Profession,[Raped in front of my girlfriend. feeling like...,"[ \n\nI don't know what to say or do, I just f...","[SuicideWatch, Needafriend, Needafriend, gainit]"
4,Oels2,[“If you truly wanted to kill yourself and was...,"[Yeah because I DONT WANT TO FUCKING DO IT, bu...","[SuicideWatch, depression, depression, depress..."
...,...,...,...,...
442,OmnisMorir,"[I lived, Overdosing Soon., I lied, but today ...","[I wrote a post [On March 19, 2020](https://ww...","[SuicideWatch, SuicideWatch, SuicideWatch, Sui..."
443,AugustIsLonely,"[So how long until it “gets better”?, What’s a...","[Why should one not consider suicide?, , Fuck ...","[SuicideWatch, AskReddit, lonely, findareddit,..."
444,schrodingerscat15,"[Always changing mind over suicide, I wanna se...",[Ever had this feeling? One moment you feel a ...,"[SuicideWatch, Avatar_Kyoshi, korrasami, Avata..."
445,95girl,"[HiyajoSafina!, Okakuri's tsundere child, Aaaa...","[, , , Some backstory is needed here.\n\nI'm a...","[steinsgate, steinsgate, steinsgate, SuicideWa..."
446,LUVVERY,"[Just like some pet owners don't deserve pets,...","[[removed], , , crippled physically or mentall...","[Showerthoughts, Piracy, EtikaRedditNetwork, A..."

In [16]:
# for comment in reddit.redditor("spez").comments.new(limit=10):
#     print(comment.body.split("\n", 1)[0][:79])

In [17]:
# for comment in reddit.redditor("spez").stream.comments():
#     print(comment)

In [18]:
# # for submission in reddit.redditor("Bittybot5000").submissions.top("all"):
#     print(submission.title)

In [19]:
# ti

In [20]:
# te

In [21]:
# len(user_df['title'][444])

In [29]:
#user_df.to_csv("userpost.csv")

In [9]:
import nltk

In [84]:
#xyz

,redditor,title,text,subreddit
0,bird-sniffer,"[Korean High School Life Starter Pack, ""What L...","[, , 16 y.o. from South Korea here. I failed e...","[starterpacks, starterpacks, SuicideWatch, sta..."
1,Throw6524285,[My girlfriend killed herself a week after we ...,[Hello. I don't really know how to start this....,[SuicideWatch]
2,cleopatra_97,[Anyone else not want to die and not want to k...,"[, Hi - I’m a 22F and have been proposed to by...","[SuicideWatch, MuslimMarriage, MakeupAddiction..."
3,Fantastic-Profession,[Raped in front of my girlfriend. feeling like...,"[ \n\nI don't know what to say or do, I just f...","[SuicideWatch, Needafriend, Needafriend, gainit]"
4,Oels2,[“If you truly wanted to kill yourself and was...,"[Yeah because I DONT WANT TO FUCKING DO IT, bu...","[SuicideWatch, depression, depression, depress..."
5,hddineejbe,[I’m starting to feel like I’m meant to commit...,"[, I’m still not entirely sure I’m trans, even...","[SuicideWatch, asktransgender, SuicideWatch, S..."
6,Alexut-,"[pretty much, i swear to god if there's an aft...","[, if i go through all the fucking trouble of ...","[traaaaaaannnnnnnnnns, SuicideWatch, MadeOfSty..."
7,im-not-worth-it,[I feel embarrassed but....does anyone else ge...,"[, , , , I’m turning 26 this summer and I’ve n...","[SuicideWatch, Atlanta, houston, houston, dati..."
8,ManiacalSuicidal,"[Just called the suicide hotline, When you're ...",[... and was asked to please 'watch my languag...,"[SuicideWatch, SuicideWatch, BPD4BPD, SuicideW..."
9,QandeelH,[I’ve seen child porn on the internet. I will ...,[I saw it on twitter. Multiple accounts. I cyb...,"[SuicideWatch, PrettyGirls, lonely, Parakeets,..."

# Cleaning of Data

In [9]:
abc.dtypes

title                   object
text                    object
time            datetime64[ns]
num_comments             int64
num_upvotes              int64
upvote_ratio           float64
redditor                object
dtype: object

In [10]:
abc=abc[['title','text','redditor']]
abc

,title,text,redditor
0,I'm trapped,16 y.o. from South Korea here. I failed everyt...,bird-sniffer
1,My girlfriend killed herself a week after we b...,Hello. I don't really know how to start this. ...,Throw6524285
2,Anyone else not want to die and not want to ki...,,cleopatra_97
3,Raped in front of my girlfriend. feeling like ...,"\n\nI don't know what to say or do, I just fe...",Fantastic-Profession
4,“If you truly wanted to kill yourself and wasn...,"Yeah because I DONT WANT TO FUCKING DO IT, but...",Oels2
...,...,...,...
495,I lived,"I wrote a post [On March 19, 2020](https://www...",OmnisMorir
496,So how long until it “gets better”?,Why should one not consider suicide?,AugustIsLonely
497,Always changing mind over suicide,Ever had this feeling? One moment you feel a s...,schrodingerscat15
498,"I have never had affection in my life, respect...","Some backstory is needed here.\n\nI'm a girl, ...",95girl
499,im extremely tired.,"Not even sure if i'll make it past today, im e...",LUVVERY

In [11]:
import re
import string

def clean_text_round1(text):
    '''Make text lowercase, remove text in square brackets, remove punctuation and remove words containing numbers.'''
    text = text.lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    #text = re.sub('\w*\d\w*', '', text)
    return text

round1 = lambda x: clean_text_round1(x)

In [12]:
data_clean_title = pd.DataFrame(abc.title.apply(round1))
data_clean_text=pd.DataFrame(abc.text.apply(round1))
data_clean=data_clean_title.join(data_clean_text)
data_clean

,title,text
0,im trapped,16 yo from south korea here i failed everythin...
1,my girlfriend killed herself a week after we b...,hello i dont really know how to start this i g...
2,anyone else not want to die and not want to ki...,
3,raped in front of my girlfriend feeling like g...,\n\ni dont know what to say or do i just feel...
4,“if you truly wanted to kill yourself and wasn...,yeah because i dont want to fucking do it but ...
...,...,...
495,i lived,i wrote a post httpswwwredditcomrsuicidewatchc...
496,so how long until it “gets better”,why should one not consider suicide
497,always changing mind over suicide,ever had this feeling one moment you feel a st...
498,i have never had affection in my life respect ...,some backstory is needed here\n\nim a girl in ...
499,im extremely tired,not even sure if ill make it past today im exh...

In [129]:
def clean_text_round2(text):
    '''Get rid of some additional punctuation and non-sensical text that was missed the first time around.'''
    #print(text)
    text = re.sub('[‘’“”…]', '', text)
    text = re.sub('\n', ' ', text)
    return text

round2 = lambda x: clean_text_round2(x)

In [130]:
# Let's take a look at the updated text
data_clean_title2 = pd.DataFrame(data_clean_title.title.apply(round2))
data_clean_text2= pd.DataFrame(data_clean_text.text.apply(round2))
data_clean=data_clean_title2.join(data_clean_text2)
data_clean
pqr=copy.deepcopy(data_clean)
pqr

,title,text
0,im trapped,16 yo from south korea here i failed everythin...
1,my girlfriend killed herself a week after we b...,hello i dont really know how to start this i g...
2,anyone else not want to die and not want to ki...,
3,raped in front of my girlfriend feeling like g...,i dont know what to say or do i just feel l...
4,if you truly wanted to kill yourself and wasnt...,yeah because i dont want to fucking do it but ...
...,...,...
495,i lived,i wrote a post httpswwwredditcomrsuicidewatchc...
496,so how long until it gets better,why should one not consider suicide
497,always changing mind over suicide,ever had this feeling one moment you feel a st...
498,i have never had affection in my life respect ...,some backstory is needed here im a girl in my...
499,im extremely tired,not even sure if ill make it past today im exh...

# Tokenizing

In [131]:
import nltk
from nltk.stem import PorterStemmer
from nltk.tokenize import sent_tokenize, word_tokenize
ps = PorterStemmer()

In [132]:
from nltk.stem import PorterStemmer
stemming = PorterStemmer()
def clean_text_round3(text):
    
    #print(text)
    #text = re.sub('[‘’“”…]', '', text)
    #text = re.sub('\n', '', text)
    text = nltk.word_tokenize(text)
    #text=ps.stem(text)
    return text

round3 = lambda x: clean_text_round3(x)

In [133]:
data_clean_title3 = pd.DataFrame(data_clean_title2.title.apply(round3))
data_clean_text3= pd.DataFrame(data_clean_text2.text.apply(round3))
data_clean=data_clean_title3.join(data_clean_text3)
data_clean

,title,text
0,"[im, trapped]","[16, yo, from, south, korea, here, i, failed, ..."
1,"[my, girlfriend, killed, herself, a, week, aft...","[hello, i, dont, really, know, how, to, start,..."
2,"[anyone, else, not, want, to, die, and, not, w...",[]
3,"[raped, in, front, of, my, girlfriend, feeling...","[i, dont, know, what, to, say, or, do, i, just..."
4,"[if, you, truly, wanted, to, kill, yourself, a...","[yeah, because, i, dont, want, to, fucking, do..."
...,...,...
495,"[i, lived]","[i, wrote, a, post, httpswwwredditcomrsuicidew..."
496,"[so, how, long, until, it, gets, better]","[why, should, one, not, consider, suicide]"
497,"[always, changing, mind, over, suicide]","[ever, had, this, feeling, one, moment, you, f..."
498,"[i, have, never, had, affection, in, my, life,...","[some, backstory, is, needed, here, im, a, gir..."
499,"[im, extremely, tired]","[not, even, sure, if, ill, make, it, past, tod..."

# Stemming,Removing Stop Words and Removing Links

In [134]:
#nltk.download('stopwords')

In [135]:
stops = set(stopwords.words("english"))  
stops

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [142]:
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
stops = set(stopwords.words("english"))        
stemming = PorterStemmer()
def clean_text_round4(text):
    t=[]
    for i in range(len(text)):
        if (text[i] not in stops and not text[i].startswith(('www','http'))):
            t.append(stemming.stem(text[i]))
    return t

round4 = lambda x: clean_text_round4(x)

In [143]:
data_clean_title4 = pd.DataFrame(data_clean_title3.title.apply(round4))
data_clean_text4= pd.DataFrame(data_clean_text3.text.apply(round4))
data_clean=data_clean_title4.join(data_clean_text4)
data_clean

,title,text
0,"[im, trap]","[16, yo, south, korea, fail, everyth, cant, go..."
1,"[girlfriend, kill, week, broke]","[hello, dont, realli, know, start, guess, ill,..."
2,"[anyon, els, want, die, want, kill, wish, coul...",[]
3,"[rape, front, girlfriend, feel, like, give]","[dont, know, say, feel, like, life, fall, apar..."
4,"[truli, want, kill, wasnt, seek, attent, youd,...","[yeah, dont, want, fuck, im, option, want, fee..."
...,...,...
495,[live],"[wrote, post, tell, anyon, whod, listen, go, o..."
496,"[long, get, better]","[one, consid, suicid]"
497,"[alway, chang, mind, suicid]","[ever, feel, one, moment, feel, strong, resolv..."
498,"[never, affect, life, respect, trust, abus, ga...","[backstori, need, im, girl, 20, never, friend,..."
499,"[im, extrem, tire]","[even, sure, ill, make, past, today, im, exhau..."

# Detokenizing

In [144]:
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
stops = set(stopwords.words("english"))        
stemming = PorterStemmer()
def clean_text_round5(text):
    txt=''
    for i in range(len(text)):
        txt=" ".join([txt, text[i]])
    return txt

round5 = lambda x: clean_text_round5(x)

In [145]:
data_clean_title5 = pd.DataFrame(data_clean_title4.title.apply(round5))
data_clean_text5= pd.DataFrame(data_clean_text4.text.apply(round5))
data_clean=data_clean_title5.join(data_clean_text5)
data_clean

,title,text
0,im trap,16 yo south korea fail everyth cant go colleg...
1,girlfriend kill week broke,hello dont realli know start guess ill tell m...
2,anyon els want die want kill wish could stop ...,
3,rape front girlfriend feel like give,dont know say feel like life fall apart three...
4,truli want kill wasnt seek attent youd tell o...,yeah dont want fuck im option want feel stop ...
...,...,...
495,live,wrote post tell anyon whod listen go overdos ...
496,long get better,one consid suicid
497,alway chang mind suicid,ever feel one moment feel strong resolv live ...
498,never affect life respect trust abus gaslit w...,backstori need im girl 20 never friend never ...
499,im extrem tire,even sure ill make past today im exhaust live...

# Document-Term Matrix

For many of the techniques we'll be using in future notebooks, the text must be tokenized, meaning broken down into smaller pieces. The most common tokenization technique is to break down text into words. We can do this using scikit-learn's CountVectorizer, where every row will represent a different document and every column will represent a different word.

In addition, with CountVectorizer, we can remove stop words. Stop words are common words that add no additional meaning to text such as 'a', 'the', etc.

In [140]:
from sklearn.feature_extraction.text import CountVectorizer
# We are going to create a document-term matrix using CountVectorizer, and exclude common English stop words
cv = CountVectorizer(stop_words='english')
data_cv = cv.fit_transform(data_clean.title)
data_dtm = pd.DataFrame(data_cv.toarray(), columns=cv.get_feature_names())
data_dtm.index = data_clean.index
data_dtm

,10,100,1140,12,13,14f,15,16,16m,1st,...,ye,yea,yeah,year,yell,yesterday,yo,youd,youll,young
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
496,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
497,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
498,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
499,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [141]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(stop_words='english')
data_cv = cv.fit_transform(data_clean.text)
data_dtm = pd.DataFrame(data_cv.toarray(), columns=cv.get_feature_names())
data_dtm.index = data_clean.index
data_dtm

,000,025mg,10,100,1000,10000,100x,1020,1030pm,10hour,...,yowan,yr,zeal,zealand,zero,zest,zip,zombi,zone,zyprexa
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
496,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
497,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
498,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
499,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0